using System.Text;
using System.Text.RegularExpressions;

namespace PXReprise.Search;

/// <summary>A search cannot be set up as asked: the pinned MetaMorpheus does not have a setting, or a value is invalid.</summary>
public sealed class SearchSetupException(string message) : Exception(message);

/// <summary>The task kinds the engine drives, and the file name MetaMorpheus's <c>CMD -g</c> writes for each.</summary>
public enum TaskKind { Calibration, Gptmd, Search }

/// <summary>
/// What the engine changes in MetaMorpheus's default task files. Everything else keeps the pinned engine's default:
/// the files are generated by <c>CMD -g</c> and only these settings are edited (aging search_mm.py, the reference
/// implementation this reproduces byte for byte).
/// </summary>
public sealed record TaskSettings(
    int MaxThreads,
    bool MatchBetweenRuns,
    IReadOnlyList<string> GptmdExtraMods,
    string? SearchType = null,
    string? SpectralLibraryMode = null,   // "write" | "update" | null (no library)
    string? ProductMassTolerance = null,  // written exactly as MetaMorpheus writes one, e.g. "±0.3500 Absolute"
    string? PrecursorMassTolerance = null);

public static class TaskFiles
{
    public static readonly IReadOnlySet<string> SearchTypes = new HashSet<string> { "Classic", "Modern", "NonSpecific" };

    public static string FileName(TaskKind kind) => kind switch
    {
        TaskKind.Calibration => "CalibrationTask.toml",
        TaskKind.Gptmd => "GptmdTask.toml",
        TaskKind.Search => "SearchTask.toml",
        _ => throw new ArgumentOutOfRangeException(nameof(kind)),
    };

    /// <summary>
    /// Applies <paramref name="s"/> to one default task file's text. Returns the new text and a note per GPTMD
    /// modification added. The text is edited line-wise with anchored patterns, never re-serialised, so every value the
    /// engine does not name stays byte-identical to MetaMorpheus's own output.
    /// </summary>
    public static (string Text, IReadOnlyList<string> AddedMods) Edit(string text, TaskKind kind, TaskSettings s,
        IReadOnlySet<(string Category, string Name)> knownMods)
    {
        // The file keeps its own line endings. MetaMorpheus writes CRLF on Windows, and .NET's multiline '$' does not
        // match before '\r', so edit LF text and restore; the Python reference does the same through universal newlines.
        bool crlf = text.Contains("\r\n");
        if (crlf) text = text.Replace("\r\n", "\n");
        var (edited, addedMods) = EditLf(text, kind, s, knownMods);
        return (crlf ? edited.Replace("\n", "\r\n") : edited, addedMods);
    }

    private static (string Text, IReadOnlyList<string> AddedMods) EditLf(string text, TaskKind kind, TaskSettings s,
        IReadOnlySet<(string Category, string Name)> knownMods)
    {
        var added = new List<string>();
        text = Replace(text, @"^MaxThreadsToUsePerFile = \d+$", $"MaxThreadsToUsePerFile = {s.MaxThreads}", "MaxThreadsToUsePerFile",
            exactlyOne: false);

        if (kind == TaskKind.Gptmd && s.GptmdExtraMods.Count > 0)
            (text, added) = AddGptmdMods(text, s.GptmdExtraMods, knownMods);

        if (kind == TaskKind.Search)
        {
            text = Replace(text, @"^MatchBetweenRuns = \w+$", $"MatchBetweenRuns = {Bool(s.MatchBetweenRuns)}", "MatchBetweenRuns",
                exactlyOne: false);
            if (s.SearchType is { } st)
            {
                if (!SearchTypes.Contains(st))
                    throw new SearchSetupException($"search type must be one of {string.Join(", ", SearchTypes)}, not '{st}'");
                text = Replace(text, "^SearchType = \".*\"$", $"SearchType = \"{st}\"", "SearchType", exactlyOne: true);
            }
            // The two library switches, on the SEARCH task only. Never both true: MetaMorpheus acts on them
            // independently and would write two libraries (aging D33).
            if (s.SpectralLibraryMode is { } mode)
            {
                if (mode is not ("write" or "update"))
                    throw new SearchSetupException($"spectral library mode must be write or update, not '{mode}'");
                text = Replace(text, @"^WriteSpectralLibrary = \w+$", $"WriteSpectralLibrary = {Bool(mode == "write")}",
                    "WriteSpectralLibrary", exactlyOne: true);
                text = Replace(text, @"^UpdateSpectralLibrary = \w+$", $"UpdateSpectralLibrary = {Bool(mode == "update")}",
                    "UpdateSpectralLibrary", exactlyOne: true);
            }
        }

        // Tolerance overrides apply to EVERY task. The "= " in the pattern keeps them off ProductMassTolerance_LowRes.
        if (s.ProductMassTolerance is { } pmt)
            text = Replace(text, "^ProductMassTolerance = \".*\"$", $"ProductMassTolerance = \"{pmt}\"", "ProductMassTolerance", exactlyOne: true);
        if (s.PrecursorMassTolerance is { } prt)
            text = Replace(text, "^PrecursorMassTolerance = \".*\"$", $"PrecursorMassTolerance = \"{prt}\"", "PrecursorMassTolerance", exactlyOne: true);

        return (text, added);
    }

    /// <summary>
    /// Appends <c>category&lt;TAB&gt;name</c> entries to <c>ListOfModsGptmd</c>. The TOML stores the list as one string
    /// with the TAB as a literal backslash-t and entries separated by two of them. A name the pinned MetaMorpheus does
    /// not define is refused: MetaMorpheus would drop it silently, which is how the GG remnant went unsearched (aging D40).
    /// </summary>
    public static (string Text, List<string> Added) AddGptmdMods(string text, IReadOnlyList<string> extra,
        IReadOnlySet<(string Category, string Name)> knownMods)
    {
        var m = Regex.Match(text, "^ListOfModsGptmd = \"(.*)\"$", RegexOptions.Multiline);
        if (!m.Success) throw new SearchSetupException("no ListOfModsGptmd line in the GPTMD task");
        var entries = m.Groups[1].Value.Split(@"\t\t").Where(e => e.Length > 0).ToList();
        var added = new List<string>();
        foreach (string item in extra)
        {
            int tab = item.IndexOf('\t');
            string cat = tab < 0 ? item : item[..tab], name = tab < 0 ? "" : item[(tab + 1)..];
            if (!knownMods.Contains((cat, name)))
                throw new SearchSetupException($"GPTMD modification '{cat}' / '{name}' is not defined in the pinned MetaMorpheus's Mods files");
            string entry = $@"{cat}\t{name}";
            if (!entries.Contains(entry))
            {
                entries.Add(entry);
                added.Add(item);
            }
        }
        string list = string.Join(@"\t\t", entries);
        return (text[..m.Groups[1].Index] + list + text[(m.Groups[1].Index + m.Groups[1].Length)..], added);
    }

    /// <summary>
    /// (category, "ID on TG") for every modification in a MetaMorpheus Mods folder (<c>Mods/*.txt</c>): the names
    /// <c>ListOfModsGptmd</c> uses, taken from the program that will read them.
    /// </summary>
    public static IReadOnlySet<(string Category, string Name)> KnownMods(string modsDir)
    {
        var found = new HashSet<(string, string)>();
        foreach (string f in Directory.EnumerateFiles(modsDir, "*.txt").OrderBy(f => f, StringComparer.Ordinal))
        {
            string? id = null, cat = null;
            List<string>? targets = null;
            foreach (string line in File.ReadLines(f, Encoding.UTF8))
            {
                if (line.StartsWith("ID   ", StringComparison.Ordinal)) { id = line[5..].Trim(); targets = null; cat = null; }
                else if (line.StartsWith("TG   ", StringComparison.Ordinal))
                    targets = line[5..].Split(" or ").Select(t => t.Trim().TrimEnd('.')).ToList();
                else if (line.StartsWith("MT   ", StringComparison.Ordinal)) cat = line[5..].Trim();
                else if (line.StartsWith("//", StringComparison.Ordinal) && id is not null && targets is not null && cat is not null)
                {
                    foreach (string t in targets) found.Add((cat, $"{id} on {t}"));
                    id = null; targets = null; cat = null;
                }
            }
        }
        return found;
    }

    private static string Bool(bool b) => b ? "true" : "false";

    private static string Replace(string text, string pattern, string replacement, string setting, bool exactlyOne)
    {
        int n = 0;
        string result = Regex.Replace(text, pattern, _ => { n++; return replacement; }, RegexOptions.Multiline);
        if (exactlyOne && n != 1)
            throw new SearchSetupException(
                $"expected exactly one {setting} line, replaced {n}: the pinned MetaMorpheus does not have the setting this code was written for");
        return result;
    }
}
